### ISSUE TITLE
Scanner not working after recent Update

### ISSUE THREAD

**Issue by Joweide** [sneakypete81/updatescanner#232]
Hi there,

After the latest Update of Firefox, you also requested to update your scanner. Since then:

- the scanner doesn't scan all updated pages
- doesn't automatically display the updated and marked versions of the websites.

I have updated both Firefox and Scanner - anything more I need to do (hopefully not to redo the monitorng list...)

Best regards

Joachim

**Comment by sneakypete81** [comment]
To help explain the issue, please include the following:
 * Firefox version:
 * Update Scanner version:

#### Steps to reproduce the problem:
[Include webpage URL, if applicable]


#### What you expected to happen:


#### What actually happened:
[Include a screenshot]

**Comment by Joweide** [comment]
Here you go with the info requested:

*Joachim*

> To help explain the issue, please include the following:
>
>    - Firefox version:
>    ​ Version 59.0.2 ​
>    - Update Scanner version:
>    ​ 4.2.1 ​
>
> Steps to reproduce the problem:
>
> [Include webpage URL, if applicable]
> ​
>
> *All URLs​*
>
> What you expected to happen:
> ​
>

The former versions scanned my list of websites according to my definition.
> Once a website was updated, it appeared as changed and marked in the list
> (both in the extension and the side window). If I clicked on the website it
> showed directly with the marked update.
> What actually happened:
> ​
>

Websites are not scanned anymore, no updates show up though the content had
> been updated.​
>
> ​If a website is shown as updated, I click on it, but the screen stays
> ​white. I have to conventionally open the website to see the changes.
>
[Include a screenshot]
>
​Thanks for taking care!

Joachim​

**Comment by keybored13** [comment]
I also am using Firefox 59.0.2 ​and did the update and can no longer can see any sites linked on the sidebar.  Just a message that says - "Can't see your scan list?  Upgrade Scanner 4" but I already upgraded it.

**Comment by keybored13** [comment]
Update:  Can confirm that at least one of my selected pages has been updated (red numbers are on the tab) so it seems it is just the sidebar information that is not working.

**Comment by Joweide** [comment]
I can also confirm that several website have been updated in fact - but the
scanner shows no results. I'm doing it manually at the moment - but this
takes much longer, of course. A pity the Scanner isn't functioning as
before.

Best jow

*Joachim O. Weidemann*

Publisher & Editor
www.ieu-monitoring.com



*IEU Monitoring* and *IEU Agenda* are product lines of:
Comecon Media GmbH - Media uniting Europe, Open to the World

IEU.Monitoring Brussels office:
c/o dpa Deutsche Presse-Agentur GmbH
IPC, Boulevard Charlemagne 1 - 1040 Brussels
3rd flour

Comecon.Media GmbH
www.comeconmedia.com
Grunerstraße 133
40239 Düsseldorf
Germany
CEO: Joachim Weidemann
j.weidemann@comeconmedia.com
Mobil: +49 175 292.57.75

Registered at Amtsgericht Düsseldorf: HRB 58263
International VAT ID No: DE258787345




2018-04-09 10:26 GMT+02:00 keybored13 <notifications@github.com>:

**Comment by jsteffl** [comment]
We might be looking on several different issues (although I don't think so) but if I put some highly updated site (e.g. msn.com) with high scanning period (15 minutes) and low change threshold it doesn't show any update (neither signals there was actual update) after enabling private mode in FF 59.0.2:

![updatescanner-4-2-1-firefox-59-0-2-private-mode-issue_20180409_1](https://user-images.githubusercontent.com/8927033/38487889-016b5e50-3be2-11e8-825f-86ae6b6ab85c.png)

**Comment by Joweide** [comment]
Hi there, Scanner seems to improve. Got Update notices from 36 of the
websites I am scanning. Thanks for you help, so far. Hope we'll get to a
100%... Cheers Joachim

*Joachim O. Weidemann*

Publisher & Editor
www.ieu-monitoring.com



*IEU Monitoring* and *IEU Agenda* are product lines of:
Comecon Media GmbH - Media uniting Europe, Open to the World

IEU.Monitoring Brussels office:
c/o dpa Deutsche Presse-Agentur GmbH
IPC, Boulevard Charlemagne 1 - 1040 Brussels
3rd flour

Comecon.Media GmbH
www.comeconmedia.com
Grunerstraße 133
40239 Düsseldorf
Germany
CEO: Joachim Weidemann
j.weidemann@comeconmedia.com
Mobil: +49 175 292.57.75

Registered at Amtsgericht Düsseldorf: HRB 58263
International VAT ID No: DE258787345




2018-04-07 12:08 GMT+02:00 sneakypete81 <notifications@github.com>:

**Comment by ds33** [comment]
I'm having this problem on both my Mac and my Windows 10 machine; it seems to be related to permissions. I can force update scanner to run by opening one of the sidebar tabs and then telling it to update all tabs, but when I open a site from the sidebar it asks "Will you allow c7d4abc2-ab65-49cd-a502-8ca3bc4d9f23 to store data on your computer?" (I assume that text string is the folder I have for Update Scanner; I don't know if it's the same on all computers.) I click "Allow Storing Data" and it updates. But once I've closed and reopened Firefox Update Scanner doesn't run until I once again open a site from the Update Scanner sidebar and agree to the permission.
I do have Firefox set to clear all private data every time I close it, but this wasn't a problem before the most recent Update Scanner update.
Thanks.

**Comment by Joweide** [comment]
Yesterday, the scanner resumed his work on my web sources - catching appr. 80% of the updated websites. I don’t know what you improved already - but THANKS! Well done. It might have helped though that I emptied all caches, histories etc in Firefox.
Hope it’ll work for all of you, too. It’s a great tool!! 

Joachim O. Weidemann
Mobile: +49 175 292.57.75
Sent from my SmartPhone - please accept my apologies for any misspellings.

The information in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. Access to this e-mail by anyone else is unauthorized. If you receive this e-mail in error, please delete it and notify me by return.

Am 11.04.2018 um 16:49 schrieb ds33 <notifications@github.com>:

I'm having this problem on both my Mac and my Windows 10 machine; it seems to be related to permissions. I can force update scanner to run by opening one of the sidebar tabs and then telling it to update all tabs, but when I open a site from the sidebar it asks "Will you allow c7d4abc2-ab65-49cd-a502-8ca3bc4d9f23 to store data on your computer?" (I assume that text string is the folder I have for Update Scanner; I don't know if it's the same on all computers.) I click "Allow Storing Data" and it updates. But once I've closed and reopened Firefox Update Scanner doesn't run until I once again open a site from the Update Scanner sidebar and agree to the permission.
I do have Firefox set to clear all private data every time I close it, but this wasn't a problem before the most recent Update Scanner update.
Thanks.

**Comment by zenxtang** [comment]
I could be wrong, but it seems whatever changed in 4.2.1 introduced the scan issue. I rolled Update Scanner back to 4.2.0 in Firefox 59.0.2 and my pages are scanning and loading. It must have something to do with the extra permission it asked for; something about storing client-side data.

**Comment by jsteffl** [comment]
Thx @zenxtang , I don't know why I missed such obvious test to do and I can confirm that scanner v4.2.0 seems to be working without issues even on latest Firefox 59.0.2. So it points more to bug/misconfiguration of add-on, at least on certain Firefox and OS set-ups. I hope @sneakypete81 will be able to find this and fix, I'm ready to provide more support if needed, just tell me what information is needed.

**Comment by sneakypete81** [comment]
Thanks everyone for your detailed reports. I'm sorry that you've all been having problems.

Update Scanner 4.2.1 now uses IndexedDB for storing page data - this was a necessary change as it fixed various performance and data integrity problems. Unfortunately it seems to cause problems when used in conjunction with Private Browsing. I've created a new issue for Private Browsing support, see #234.

@Joweide I'm glad your problem has been resolved, I can't see what the cause might have been.

@jsteffl Nice detective work, thanks.

@keybored13 - are you using Private Browsing? Try opening the Browser Console before you open the sidebar, and see if any errors appear. Also, try to reproduce your problem in a fresh profile with no other addons installed (https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles). Please raise a new issue if you are still having problems.

@ds33 & @zenxtang  - Can you please check the exact settings you have selected in the History section of your Privacy and Security preferences tab? Please also follow the instructions above and open a new issue if necessary.

**Comment by zenxtang** [comment]
I have Firefox set to "Always use private browsing mode" so as you have determined, that is the issue.

**Comment by keybored13** [comment]
Hi sneakypete81.  Thanks for your reply.

I am not using private browsing and still have the issue that it does not show anything on the sidebar other than the message to upgrade.  

I will try out a new profile tomorrow.

**Comment by ds33** [comment]
I'm not in private browsing mode, but I have the History setting in "Privacy & Security" set to "Clear History When Firefox Closes" with everything checked in the Settings for Clearing History. I tried unchecking "Site Preferences" under "Data" but this didn't seem to fix it. Do you think I need to uncheck "Offline Website Data" as well or is it likely another setting?
Thanks.

**Comment by gdevitis** [comment]
After upgrading to 4.2.1, even without Private Browsing Mode, Scanner Update has problems. Especially when I open Firefox and visualize the update scanner sidebar, after clicking in a site on the sidebar, the notification appears to allow saving to the addon.
If I don't authorize (it happens every time I start up), the addon doesn't work.

**Comment by sneakypete81** [comment]
@gdevitis : Please try to reproduce your problem in a fresh profile with no other addons installed (https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles). Please raise a new issue if you are still having problems.

**Comment by gdevitis** [comment]
With a new profile, if in about:preferences#privacy, "Firefox will use custom setting for history", enable "clear history when Firefox closes" and in "Settings" the option "Data Preference" is enabled, when I open Firefox and click on a site in "update scanner sidebar" , a notification dialog appears to "allow storing Data". Without this permission (every time I open Firefox), Update Scanner doesn't work.

**Comment by sneakypete81** [comment]
I think the causes of these issues are now all captured in more specific issues (#234, #235). Thanks everyone for reporting these.
